---
title: "Fossil herbivory v3"
author: "Anshuman"
date: "1/18/2021"
output: html_document
---


```{r}
filenets = list.files(path="data/Localities/select", pattern="*.csv", full.names=T)
filenets2 = list.files(path="data/Localities/select", pattern="*.csv", full.names=F)
lengthi=NULL
for (i in 1:length(filenets)){
  nam=paste(filenets[i])
  netcurr=read.csv(nam, header=T)
  colnames(netcurr)[1]="ID"
  nam2=strsplit(filenets2[i],".csv")[[1]]
  bstill=c(nam2,nrow(netcurr))
  lengthi=rbind(lengthi,bstill)
}

rownames(lengthi)=NULL
leng2=lengthi
colnames(leng2)=c("web", "samples")
leng2=as.data.frame(leng2)
leng2$samples=as.numeric(leng2$samples)
leng3=leng2[order(leng2$samples),]
```


```{r}
allseq=c(seq(100,500,50),seq(600,1000,100),seq(1200,2000,200), seq(2500,4000,500), seq(5000,7500,1000))

custlen=function(x){
  return(length(allseq[allseq<x]))
}

newcustlen=function(x){
  if (x<500){return("A")}
  if (x>=500 & x<1000){return("B")}
  if (x>=1000 & x<2000){return("C")}
  if (x>=2000 & x<4000){return("D")}
  if (x>=4000 & x<9000){return("E")}
}

```

```{r}
grp=NULL
for (i in 1:61){
  grp=c(grp,newcustlen(leng2$samples[i]))
}
```



```{r}
set.seed(1)

networklevlist=NULL
networklevmean=NULL
networklevelvar=NULL

library(Rfast)

for (i in 1:length(filenets)){
  nam=paste(filenets[i])
  netcurr=read.csv(nam, header=T)
  colnames(netcurr)[1]="ID"
  netcurr2=netcurr %>% group_by(ID) %>%  summarise_if(is.numeric, sum, na.rm = TRUE)
  netmat = data.matrix(netcurr2[,-c(1)], rownames.force = NA)
  rownames(netmat)= netcurr2$ID
  
  minrow=300
  
  netpro=NULL
  allnames=cbind(rownames(netmat),0)
  colnames(allnames)=c("ID","Nul")
  allnames=as.data.frame(allnames)
  
  for (j in 1:500){
        q2=sample(nrow(netcurr), minrow, replace=F)
        datarand=netcurr[q2,]
        netrand=datarand %>% group_by(ID) %>%  summarise_if(is.numeric, sum, na.rm = TRUE)
        netrandfinal=left_join(allnames,netrand, by="ID")
        netrandfinal[is.na(netrandfinal)] <- 0
        netrandfinal=netrandfinal[,-c(1:2)]
        netrandfinal=data.matrix(netrandfinal)
        netpro=rbind(netpro,networklevel(netrandfinal, nrep=20))
        
        if (j %% 10 == 0){print(paste("Sequence", " ", j))}
  }
  
  
  
  nam2=strsplit(filenets2[i],".csv")[[1]]
  
  networklevmean=rbind(networklevmean,c(nam2,colmeans(netpro)))
  networklevelvar=rbind(networklevelvar,c(nam2,colVars(netpro, std = F)))
  
  networklevlist[[i]]=netpro
 
  print(i)
}

colnames(networklevmean)=c("Web",colnames(netpro))
colnames(networklevelvar)=c("Web",colnames(netpro))
```


```{r}
set.seed(1)

networklevlist=NULL
#networklevmean=NULL
#networklevelvar=NULL

library(Rfast)
#length(filenets)
for (i in 1:2){
  netpro=NULL
  nam=paste(filenets[i])
  netcurr=read.csv(nam, header=T)
  colnames(netcurr)[1]="ID"
  netcurr2=netcurr %>% group_by(ID) %>%  summarise_if(is.numeric, sum, na.rm = TRUE)
  netmat = data.matrix(netcurr2[,-c(1)], rownames.force = NA)
  rownames(netmat)= netcurr2$ID
  
 
  
  seqsp=NULL
  allnames=cbind(rownames(netmat),0)
  colnames(allnames)=c("ID","Nul")
  allnames=as.data.frame(allnames)
  #custlen(leng2$samples[i])
  
  
  for (num in 1:2){
    minrow=allseq[num]
  
    for (j in 1:50){
        q2=sample(nrow(netcurr), minrow, replace=F)
        datarand=netcurr[q2,]
        netrand=datarand %>% group_by(ID) %>%  summarise_if(is.numeric, sum, na.rm = TRUE)
        netrandfinal=left_join(allnames,netrand, by="ID")
        netrandfinal[is.na(netrandfinal)] <- 0
        netrandfinal=netrandfinal[,-c(1:2)]
        netrandfinal=data.matrix(netrandfinal)
        netpro=rbind(netpro,networklevel(netrandfinal, nrep=20))
        
        
        if (j %% 25 == 0){print(paste("Web",i,":",strsplit(filenets2[i],".csv")[[1]], "Sample size", allseq[num], "Sequence", j))}
    }
     
    seqsp=c(seqsp, rep(allseq[num], 50))
    
  }
  
  nam2=strsplit(filenets2[i],".csv")[[1]]
  
  netpro=as.data.frame(netpro)
  
  netpro$web=nam2
  
  netpro$sample.size= seqsp
  
  
  networklevlist[[i]]=netpro
 
  print(i)
}
  


#colnames(networklevmean)=c("Web",colnames(netpro))
#colnames(networklevelvar)=c("Web",colnames(netpro))
```



```{r}
#write.csv(networklev, "networklevelAll.csv")
#write.csv(higherlev,"DTlevelAll.csv")
#write.csv(plantlev, "plantlevelAll.csv")
```


```{r}
mat <- matrix(1:25, ncol = 5)
vec <- seq(2, by = 2, length = 5)

mat
vec

sweep(mat, 2, vec, `/`)
```




```{r}
filenets = list.files(path="data/Localities/select", pattern="*.csv", full.names=T)
filenets2 = list.files(path="data/Localities/select", pattern="*.csv", full.names=F)

networklevn=NULL
#higherlev2=NULL
#plantlev2=NULL

for (i in 1:length(filenets)){
  nam=paste(filenets[i])
  netcurr=read.csv(nam, header=T)
  colnames(netcurr)[1]="ID"
  netcurr2=netcurr %>% group_by(ID) %>%  summarise_if(is.numeric, sum, na.rm = TRUE)
  netmat = data.matrix(netcurr2[,-c(1)], rownames.force = NA)
  rownames(netmat)= netcurr2$ID
  
  
  
 # net=net[,-1]
  nam2=strsplit(filenets2[i],".csv")[[1]]
  #plotweb(net)
  networklevn=rbind(networklevn,c(nam2,networklevel(netmat)))
  #X=specieslevel(netmat)
  #X1=X$`higher level`
  #X2=X$`lower level`
  
  #X1$web=nam2
  #X2$web=nam2
  
  #higherlev2=rbind(higherlev2,X1)
  #plantlev2=rbind(plantlev2,X2)
  print(i)
}


#write.csv(networklev2, "networklevelAll_new.csv")
#write.csv(higherlev2,"DTlevelAll_new.csv")
#write.csv(plantlev2, "plantlevelAll_new.csv")

```



```{r}
networklevn2=networklevn[,-c(1,6)]

netwoo2=NULL
netwoodata=NULL

for (i in 1:61){
  X=data.matrix(as.data.frame(netwoo[[i]][,-c(5,48,49)]))
  X2=sweep(X, 2, as.numeric(networklevn2[i,]), `/`)
  netwoo2[[i]]=X2
  X3=as.data.frame(cbind(as.data.frame(netwoo[[i]][,c(48,49)]),X2))
  netwoodata=rbind(netwoodata,X3)
}


netwoodata2=netwoodata

tab=table(netwoodata$web)

grp2=NULL
for (i in 1:61){
  grp2=c(grp2,rep(grp[i],as.numeric(tab[i])))
}

netwoodata2$group=as.factor(grp2)
```


```{r}
 norm.interval1 = function(data, variance = var(data), conf.level = 0.95) {
 z = qnorm((1 - conf.level)/2, lower.tail = FALSE)
 xbar = mean(data)
 sdx = sqrt(variance/length(data))
 c(xbar - z * sdx)
 }

 norm.interval2 = function(data, variance = var(data), conf.level = 0.95) {
 z = qnorm((1 - conf.level)/2, lower.tail = FALSE)
 xbar = mean(data)
 sdx = sqrt(variance/length(data))
 c(xbar + z * sdx)
 }

norm.interval1(netwoodata2$C.score.LL)
mean(netwoodata2$C.score.LL)

summary(netwoodata2$C.score.LL)
```



```{r}


#summar=netwoodata2 %>% group_by(group, sample.size) %>%  summarise_if(is.numeric, mean, na.rm = TRUE)

summar2=netwoodata2 %>% group_by(sample.size) %>%  summarise_if(is.numeric, mean, na.rm = TRUE)

summardwn=netwoodata3[-which(netwoodata3$C.score.HL==Inf),] %>% group_by(sample.size) %>%  summarise_if(is.numeric, norm.interval1)

summarup=netwoodata3[-which(netwoodata3$C.score.HL==Inf),] %>% group_by(sample.size) %>%  summarise_if(is.numeric, norm.interval2)

netwoodata3=netwoodata2
netwoodata3[is.na(netwoodata3)] <- 1

numsreq=which(netwoodata2$C.score.LL>100)

cscoredel1=which(is.na(netwoodata2$C.score.HL)==TRUE)
cscoredel2=which(is.na(netwoodata2$C.score.LL)==TRUE)

summar3=netwoodata2[-numsreq,]%>% group_by( sample.size) %>%  summarise_if(is.numeric, mean, na.rm = TRUE)


x=(summar$sample.size)
y=summar$number.of.species.LL
plot(x, y, col=summar$group, cex=0.7,   pch=16, ylim=c(0,1))

plot(netwoodata2$number.of.species.LL~log10(netwoodata2$sample.size),cex=0.3, col=netwoodata2$group)



x=log10(summar2$sample.size)
y=summar2$H2
plot(x, y,pch=16, ylim=c(0,2), xlab="Log (sample size)", ylab="H2")
abline(h=1, col="red", lty=2)

library(pracma)
y=summar2$`weighted nestedness`
semilogx(summar2$sample.size, y, ylim = c(0,2), ylab = "Partner Diversity (Plants)", xlab = "Sample size", pch=16, col="indianred3")
abline(h=1, col="red", lty=2)
abline(v=300, col="blue", lty=4)


```


```{r}
y=summar$robustness.HL
semilogx(summar$sample.size, y, ylim = c(0,2), ylab = "Partner Diversity (DTs)", xlab = "Sample size", pch=16, col=summar$group)
abline(h=1, col="red", lty=2)
abline(v=300, col="blue", lty=4)
```




```{r}
hist(leng2$samples, main="Distribution of Player Ratings",xlim = c(0,7500), breaks=c(0,500,1000,2000,4000,7500), col = c("blue", "red","green", "grey"))

h=hist(leng2$sample, breaks=35, col="indianred2", xlim = c(0,7500), main = "" )
cuts <- cut(h$breaks, c(0,500,1000,2000,4000,7500))
plot(h, col=c(1:5)[cuts])
```



```{r}
#library(pracma)
y=summar3$`weighted connectance`
semilogx(summar3$sample.size, y, ylim = c(0,2), ylab = "Weighted Connectance", xlab = "Sample size", pch=16, col="indianred3")
#plot(summar3$sample.size, y, ylim = c(0,2), ylab = "Partner Diversity (Plants)", xlab = "Sample size", pch=16, col="indianred3")
arrows(summar3$sample.size, summarup$`weighted connectance`, summar3$sample.size, summardwn$`weighted connectance`, code=3, angle=90, length=0.07, col="indianred")
abline(h=1, col="red", lty=2)
abline(v=300, col="blue", lty=4)


#arrows(soil6$Glucose_conc, soil6$Bacteria1+soil6$Bacteria1_err, soil6$Glucose_conc, soil6$Bacteria1-soil6$Bacteria1_err, length=0.05, angle=90, code=3, col=2)
```



```{r}

library(ggplot2)
# Make the plot
CHL=ggplot(data=summar3, aes(x=sample.size, y=functional.complementarity.HL, ymin=summardwn$functional.complementarity.HL, ymax=summarup$functional.complementarity.HL)) + 
geom_line() + 
geom_ribbon(alpha=0.5) + 
scale_x_log10()  + 
xlab("Sample Size") + 
ylab("C-Score (DTs)")+
ylim(0,2)

 #xlab(as.expression(expression( paste("Radius (", R[500], ")") )))
CHL
```



```{r}
summargrp=netwoodata3 %>% group_by(group, sample.size) %>%  summarise_if(is.numeric, mean, na.rm = TRUE)
summargrpup=netwoodata3 %>% group_by(group, sample.size) %>%  summarise_if(is.numeric, norm.interval2)
summargrpdwn=netwoodata3 %>% group_by(group, sample.size) %>%  summarise_if(is.numeric, norm.interval1)
```

```{r}
library(pracma)
y=summargrp$robustness.HL
semilogx(summargrp$sample.size, y, ylim = c(0,2), ylab = "Resilience (DTs)", xlab = "Sample size", pch=16, col=summar$group)
#plot(summar3$sample.size, y, ylim = c(0,2), ylab = "Partner Diversity (Plants)", xlab = "Sample size", pch=16, col="indianred3")
arrows(summargrp$sample.size, summargrpup$robustness.HL, summargrp$sample.size, summargrpdwn$robustness.HL, code=3, angle=90, length=0.02, col=summar$group)
abline(h=1, col="red", lty=2)
abline(v=300, col="blue", lty=4)
```






